### ISSUE TITLE
Trezor T on devboard

### ISSUE THREAD

**Issue by hiviah** [mcudev/mcudev.github.io#1]
Hi, since I couldn't contact you via email:

I found your page with HOWTO recreate Trezor T -
https://mcudev.github.io/trezor-model-t-dev-kit/index.html

I'd like to do the same since it's a lot of pain soldering onto production board
(many things are way too small and wires fall off way too often since the
contacts are so tiny even if you glue-gun them).

So,

1. Did you need to remove the SDRAM? And remove display? Some photos are with
those, some without it, so not sure.
2. Is the removed display the same as the one on the devboard? Is it glued, i.e.
do I need to pull it off forcefully?

Thanks,
  O. Mikle

**Comment by mcudev** [comment]
Hi! Sorry, I just saw your questions.

  1. I do not believe that removing the SDRAM and display from the dev board were actually necesssary. At one time during the development process, I remember thinking that it was necesssary. But, if I remember correctly, we later fixed a code bug that caused the issue that I thought was fixed by removing those parts. I later tried the updated code on a dev board that still had the original parts and it worked. That's why I added the question: "Must I remove the SDRAM and TFT LCD + resistive touch panel that come attached to the STM32F429I-DISC1 dev board?" and answer: "No, removing those parts is optional." down in the questions section of the page.
  1. The display that comes originally on the dev board has different specs than the display module that we needed for the kit. They have different driver chips, etc... If I recall correctly, the display module that originally comes on the dev board is mostly stuck on with double sided tape. I think slow steady pressure to pull it from the board was all that was necessary. The solder connections are not very strong and will come off easily with a little pulling. Removing the SDRAM chip was trickier and cutting the leads with an x-acto knife was the quickest and easiest way for me to remove it without reflowing the solder.
